### ISSUE TITLE
Puppet module for managing configuration

### ISSUE THREAD

**Issue by pcarlisle** [rji/waylon#64]
This would help us make things a bit more self-service for our teams.

**Comment by rji** [comment]
:+1: it's definitely on the roadmap. Thanks for opening an issue for it!

**Comment by rji** [comment]
Dependent on work being done in #16.

**Comment by rji** [comment]
Module is available at https://github.com/rji/puppet-waylon. We'll be working to get this into our control repo and build some roles and profiles around it shortly.
